server:
  servlet:
    context-path: /escalux  
  port: 8090
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:~/DB_ESCALUX;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
    